version: '3.8'
services:

  # GitLab
  gitlab:
    image: 'gitlab/gitlab-ce:latest'
    restart: always
    container_name: gitlab
    hostname: '10.0.2.15'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://10.0.2.15'
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - './gitlab/config:/etc/gitlab'
      - './gitlab/logs:/var/log/gitlab'
      - './gitlab/data:/var/opt/gitlab'
    networks:
      - devsecops-network

  # GitLab Runner
  gitlab-runner-1:
    image: gitlab/gitlab-runner:alpine
    restart: always
    container_name: gitlab-runner-1
    hostname: gitlab-runner-1
    depends_on:
      - gitlab
    volumes:
     - ./config/gitlab-runner:/etc/gitlab-runner
     - /var/run/docker.sock:/var/run/docker.sock
    networks:
        - devsecops-network

networks:
  devsecops-network:
    name: devsecops-network